import{a as b,S as v,i as f}from"./assets/vendor-b42c18af.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function i(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(o){if(o.ep)return;o.ep=!0;const s=i(o);fetch(o.href,s)}})();const h="/goit-js-hw-12/assets/icon-06de2d57.svg";async function m(e,t=15,i=1){return(await b.get("https://pixabay.com/api/",{params:{key:"42554621-2fa4a31fb360b145b3c1613f4",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i,per_page:t}})).data}function p(e){return e.map(({webformatURL:t,largeImageURL:i,tags:n,likes:o,views:s,comments:c,downloads:L})=>`<li class="gallery-item">
                     <a href="${i}">
                        <img src="${t}" alt="${n}"/>
                        <div class="info-box">
                           <p class="info"><b>Likes</b> ${o}</p>
                           <p class="info"><b>Views</b> ${s}</p>
                           <p class="info"><b>Comments</b> ${c}</p>
                           <p class="info"><b>Downloads</b> ${L}</p>
                     </div>
                    </a>
                   </li>`).join("")}const g=document.querySelector("form"),u=document.querySelector("ul.gallery"),a=document.querySelector("span.loader"),r=document.querySelector('[data-action="load-more"]');let l,d;a.classList.remove("loader");r.classList.add("is-hidden");const F=new v(".gallery a",{captionsData:"alt",captionDelay:100});async function w(e){if(e.preventDefault(),u.innerHTML="",r.classList.add("is-hidden"),d=e.currentTarget.elements.search.value.trim(),d!==""){a.classList.add("loader"),l=1;try{const t=await m(d,15,l);t.totalHits!==0?(a.classList.remove("loader"),u.innerHTML=p(t.hits),r.classList.remove("is-hidden"),F.refresh()):B()}catch(t){y(t)}}g.reset()}async function S(){a.classList.add("loader"),r.classList.add("is-hidden"),l+=1;try{const e=await m(d,15,l);a.classList.remove("loader");const t=p(e.hits);u.insertAdjacentHTML("beforeend",t),r.classList.remove("is-hidden"),r.parentNode.insertBefore(a,r.nextSibling),F.refresh(),P(e.totalHits),q()}catch(e){y(e)}}async function P(e){e<=l*15&&(r.classList.add("is-hidden"),C())}function q(){const t=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t.height*3,behavior:"smooth"})}function B(){f.show({iconUrl:h,message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FFFFFF",color:"#FF6868",position:"topRight",progressBarColor:"#FFFFFF",close:!1,timeout:3e3}),a.classList.remove("loader")}function y(e){console.error(e),f.error({iconUrl:h,message:"Sorry, there was an unexpected issue running your request!",messageColor:"#FFFFFF",color:"#FF6868",position:"topRight",progressBarColor:"#FFFFFF",close:!1,timeout:3e3}),a.classList.remove("loader")}function C(){f.show({iconUrl:h,message:"We're sorry, but you've reached the end of search results",messageColor:"#FFFFFF",color:"#1E81B0",position:"topRight",progressBarColor:"#FFFFFF",close:!1,timeout:3e3})}g.addEventListener("submit",w);r.addEventListener("click",S);
//# sourceMappingURL=commonHelpers.js.map
