import{a as P,S as q,i as h}from"./assets/vendor-b42c18af.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const p="/goit-js-hw-12/assets/icon-06de2d57.svg";async function g(o,t=15,s=1){return(await P.get("https://pixabay.com/api/",{params:{key:"42554621-2fa4a31fb360b145b3c1613f4",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:t}})).data}function F(o){return o.map(({webformatURL:t,largeImageURL:s,tags:n,likes:e,views:r,comments:i,downloads:B})=>`<li class="gallery-item">
                     <a href="${s}">
                        <img src="${t}" alt="${n}"/>
                        <div class="info-box">
                           <p class="info"><b>Likes</b> ${e}</p>
                           <p class="info"><b>Views</b> ${r}</p>
                           <p class="info"><b>Comments</b> ${i}</p>
                           <p class="info"><b>Downloads</b> ${B}</p>
                     </div>
                    </a>
                   </li>`).join("")}const y=document.querySelector("form"),f=document.querySelector("ul.gallery"),m=document.querySelector("span.loader"),a=document.querySelector('[data-action="load-more"]');let c,u;l();d();const b=new q(".gallery a",{captionsData:"alt",captionDelay:100});async function C(o){if(o.preventDefault(),f.innerHTML="",console.clear(),d(),u=o.currentTarget.elements.search.value.trim(),u!==""){S(),c=1;try{const t=await g(u,15,c);t.totalHits!==0?(l(),f.innerHTML=F(t.hits),w(),b.refresh()):M(),L(t.totalHits)}catch{v()}}y.reset()}async function x(){S(),d(),c+=1;try{const o=await g(u,15,c);l();const t=F(o.hits);f.insertAdjacentHTML("beforeend",t),w(),a.parentNode.insertBefore(m,a.nextSibling),b.refresh(),L(o.totalHits),H()}catch{v()}}async function L(o){o<=c*15&&(d(),O())}function H(){const t=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t.height*3,behavior:"smooth"})}function w(){a.classList.remove("is-hidden")}function d(){a.classList.add("is-hidden")}function S(){m.classList.add("loader")}function l(){m.classList.remove("loader")}function M(){h.show({iconUrl:p,message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FFFFFF",color:"#FF6868",position:"topRight",progressBarColor:"#FFFFFF",close:!1,timeout:3e3}),l()}function v(){h.error({iconUrl:p,message:"Sorry, there was an unexpected issue running your request!",messageColor:"#FFFFFF",color:"#FF6868",position:"topRight",progressBarColor:"#FFFFFF",close:!1,timeout:3e3}),l()}function O(){h.show({iconUrl:p,message:"We're sorry, but you've reached the end of search results",messageColor:"#FFFFFF",color:"#1E81B0",position:"topRight",progressBarColor:"#FFFFFF",close:!1,timeout:3e3})}y.addEventListener("submit",C);a.addEventListener("click",x);
//# sourceMappingURL=commonHelpers.js.map
